### ISSUE TITLE
Responding to milestone 1 feedback

### ISSUE THREAD

**Issue by syadk** [UBC-MDS/532-Group21-R#6]
In response to the milestone 1 feedback found here: https://github.com/UBC-MDS/532-Group21/issues/14
Tasks marked as completed have already been implemented in milestone 2 or 3 and unchecked tasks will be done by milestone 4.

- [x] Fix grammatical errors in research questions as well as clarify what is meant by 'fund-sensitive' countries and how the dashboard will help the user
- [x] title on map and bar graph specific to year and statistic of interest
- [x] use radial buttons instead of check boxes
- [x] Add map interactivity to show country and value of statistic of interest

**Comment by eboylestanley** [comment]
All milestone 1 feedback addressed in milestone 2.  All changes were also carried forward into the R implementation.
